version: "3"

services:
  docs:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./target/xtensa-esp32-espidf/doc:/usr/share/nginx/html
  firmware:
    build: .
    ports:
      - 8001:80
    volumes:
      - ./bin:/usr/share/nginx/html