[package]
name = "rued-esp32"
version = "0.2.0"
authors = ["Michael de Silva <michael@mwdesilva.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
pio = ["esp-idf-sys/pio"]
default = ["edge-executor", "system"] # Note that edge-executor requires alloc
system = ["display-i2c"]
# system = ["display-spi"]

display-spi = ["profont", "ssd1351"]
display-i2c = ["profont", "ssd1306", "display-binary-color"]
display-binary-color = []

[dependencies]
anyhow = "1"
heapless = { version = "0.7" }
enumset = "1"
log = "0.4.17"
futures = {version = "0.3", features = ["async-await"] }
serde = { version = "1", default-features = false }
postcard = "0.7"
critical-section = "1.1"
embedded-hal = { git = "https://github.com/rust-embedded/embedded-hal" }
embedded-hal-0-2 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }
embedded-svc = { version = "0.23", features = ["nightly", "experimental"] }
esp-idf-sys = { version = "0.31.11", features = ["binstart"] }
esp-idf-svc = { version = "0.43.2", features = ["nightly", "experimental", "embassy-time-isr-queue"] }
esp-idf-hal = { version = "0.39", features = ["edge-executor", "embassy-sync", "critical-section"] }
embassy-futures = { version = "0.1" }
embassy-sync = { version = "0.1", features = ["std"] }
embassy-time = { version = "0.1" }
static_cell = { version = "1" }
edge-frame = { version = "0.4", default-features = false, features = ["assets-serve"], git = "https://github.com/ivmarkov/edge-frame" }
edge-executor = { version = "0.3", optional = true }
channel-bridge = { version = "0.1", git = "https://github.com/ivmarkov/channel-bridge", default-features = false, features = ["notification", "nightly", "embedded-svc"] }
# ruwm = { git = "https://github.com/ivmarkov/ruwm" } 

# time = { version = "0.3.17", features = ["macros"] }
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std", "wasmbind"] } 
embedded-graphics = "0.7"
display-interface = "0.4"
gfx-xtra = "0.1"
serde_json = "1.0.87"
cstr_core = "0.2.6"
uncased = { version = "0.9.7" }
shared-bus = { version = "0.2", features = ["std"] }
once_cell = "1.16.0"

# optional dependencies
profont = { version = "0.5", optional = true }
ssd1306 = { version = "0.7.0", optional = true }
ssd1351 = { version = "0.4", optional = true }

[build-dependencies]
embuild = "0.30"
anyhow = "1"
